---
- hosts: routers
  become: yes

  tasks:
    - name: Create Loopback33
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback33
            description: Ansible Andrew
            enabled: true
#            ipv4: 192.168.333.33/32


    - name: Add IP address to L44
      cisco.ios.ios_l3_interface:
        name: Loopback44
        ipv4: 192.168.44.44/32

    - name: perform show run
      ios_command:
        commands:
          - show run
#         - show start
      register: output1

    - name: print show run
      debug:
        var: output1.stdout_lines
