---
- hosts: routers
  become: yes
  gather_facts: false

  tasks:
    - name: Compare the running-config against the startup-config
      cisco.ios.ios_config:
        diff_against: startup
#      register: output
#
#    - name: print output
#      debug:
#        var: output.stdout_lines

    - name: show interfaces
      ios_command:
        commands:
          - show ip int brief
#         - show start
      register: output1

    - name: print show run
      debug:
        var: output1.stdout_lines
