---
datacenter:
  children:
    routers:
      hosts:
        sandbox-iosxe-latest-1.cisco.com
      vars:
        testVar: 999
#    switches:
#      hosts:
#        10.30.10.241:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: developer
    ansible_ssh_pass: C1sco12345
    ansible_become_password: C1sco12345
#    ntp_servers:
#      - 10.30.11.10
#      - 10.20.11.10
